# NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Unsent.Types.AddDomainRouteRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :providerConnectionId,
    :weight
  ]

  @type t :: %__MODULE__{
    :providerConnectionId => String.t,
    :weight => integer() | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.AddSuppression200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :email,
    :reason,
    :source,
    :createdAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :email => String.t,
    :reason => String.t,
    :source => String.t | nil,
    :createdAt => String.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.AddSuppressionRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :reason,
    :source
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :reason => String.t,
    :source => String.t | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateApiKey200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :token
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :token => String.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateApiKeyRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :permission
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :permission => String.t | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateCampaign200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :from,
    :subject,
    :previewText,
    :contactBookId,
    :html,
    :content,
    :status,
    :scheduledAt,
    :batchSize,
    :batchWindowMinutes,
    :total,
    :sent,
    :delivered,
    :opened,
    :clicked,
    :unsubscribed,
    :bounced,
    :hardBounced,
    :complained,
    :replyTo,
    :cc,
    :bcc,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :from => String.t,
    :subject => String.t,
    :previewText => String.t | nil,
    :contactBookId => String.t | nil,
    :html => String.t | nil,
    :content => String.t | nil,
    :status => String.t,
    :scheduledAt => DateTime.t | nil,
    :batchSize => integer(),
    :batchWindowMinutes => integer(),
    :total => integer(),
    :sent => integer(),
    :delivered => integer(),
    :opened => integer(),
    :clicked => integer(),
    :unsubscribed => integer(),
    :bounced => integer(),
    :hardBounced => integer(),
    :complained => integer(),
    :replyTo => [String.t],
    :cc => [String.t],
    :bcc => [String.t],
    :createdAt => DateTime.t,
    :updatedAt => DateTime.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateCampaignRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :from,
    :subject,
    :previewText,
    :contactBookId,
    :content,
    :html,
    :replyTo,
    :cc,
    :bcc,
    :sendNow,
    :scheduledAt,
    :batchSize
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :from => String.t,
    :subject => String.t,
    :previewText => String.t | nil,
    :contactBookId => String.t,
    :content => String.t | nil,
    :html => String.t | nil,
    :replyTo => Unsent.Types.CreateCampaignRequestReplyTo.t | nil,
    :cc => Unsent.Types.CreateCampaignRequestReplyTo.t | nil,
    :bcc => Unsent.Types.CreateCampaignRequestReplyTo.t | nil,
    :sendNow => boolean() | nil,
    :scheduledAt => String.t | nil,
    :batchSize => integer() | nil
  }


  def decode(value) do
    value
     
     
     
  end
end

defmodule Unsent.Types.CreateCampaignRequestReplyTo do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateContact200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :contactId
  ]

  @type t :: %__MODULE__{
    :contactId => String.t | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateContactBook200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :emoji,
    :properties,
    :teamId,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :emoji => String.t,
    :properties => any() | nil,
    :teamId => String.t,
    :createdAt => String.t,
    :updatedAt => String.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateContactBookRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :emoji,
    :properties
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :emoji => String.t | nil,
    :properties => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateContactRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :firstName,
    :lastName,
    :properties,
    :subscribed
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :firstName => String.t | nil,
    :lastName => String.t | nil,
    :properties => %{optional(String.t) => String.t} | nil,
    :subscribed => boolean() | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateDomainRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :providerConnectionId
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :providerConnectionId => String.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateProviderConnectionRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :name,
    :credentials
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :name => String.t,
    :credentials => Unsent.Types.CreateProviderConnectionRequestCredentials.t
  }


  def decode(value) do
    value
     
  end
end

defmodule Unsent.Types.CreateProviderConnectionRequestCredentials do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :accessKeyId,
    :secretAccessKey,
    :region,
    :apiKey
  ]

  @type t :: %__MODULE__{
    :accessKeyId => String.t | nil,
    :secretAccessKey => String.t | nil,
    :region => String.t | nil,
    :apiKey => String.t | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateTemplate200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id
  ]

  @type t :: %__MODULE__{
    :id => String.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateTemplateRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :subject,
    :html,
    :content
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :subject => String.t,
    :html => String.t | nil,
    :content => String.t | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.CreateWebhookRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :url,
    :description,
    :eventTypes,
    :secret
  ]

  @type t :: %__MODULE__{
    :url => Uri,
    :description => String.t | nil,
    :eventTypes => [String.t],
    :secret => String.t | nil
  }


  def decode(value) do
    value
     
  end
end

defmodule Unsent.Types.DeleteWebhook200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success
  ]

  @type t :: %__MODULE__{
    :success => boolean()
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.Error do
  @moduledoc """
  Error response
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :message,
    :docs
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :message => String.t,
    :docs => String.t | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetAnalytics200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :day,
    :month
  ]

  @type t :: %__MODULE__{
    :day => [Unsent.Types.GetAnalytics200ResponseDayInner.t],
    :month => [Unsent.Types.GetAnalytics200ResponseDayInner.t]
  }


  def decode(value) do
    value
     
     
  end
end

defmodule Unsent.Types.GetAnalytics200ResponseDayInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :sent
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :sent => number()
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetApiKeys200ResponseInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :partialToken,
    :lastUsed,
    :createdAt,
    :permission
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :partialToken => String.t,
    :lastUsed => String.t | nil,
    :createdAt => String.t,
    :permission => String.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetCampaigns200ResponseInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :subject,
    :status,
    :created_at,
    :sent,
    :delivered,
    :opened,
    :clicked
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :subject => String.t,
    :status => String.t | nil,
    :created_at => String.t,
    :sent => number() | nil,
    :delivered => number() | nil,
    :opened => number() | nil,
    :clicked => number() | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetContactBook200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :emoji,
    :properties,
    :teamId,
    :createdAt,
    :updatedAt,
    :details
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :emoji => String.t,
    :properties => any() | nil,
    :teamId => String.t,
    :createdAt => String.t,
    :updatedAt => String.t,
    :details => Unsent.Types.GetContactBook200ResponseDetails.t
  }


  def decode(value) do
    value
     
  end
end

defmodule Unsent.Types.GetContactBook200ResponseDetails do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :totalContacts,
    :unsubscribedContacts,
    :campaigns
  ]

  @type t :: %__MODULE__{
    :totalContacts => number(),
    :unsubscribedContacts => number(),
    :campaigns => [any()]
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetDomainAnalytics200ResponseInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :date,
    :sent,
    :delivered,
    :opened,
    :clicked,
    :bounced,
    :complained
  ]

  @type t :: %__MODULE__{
    :date => String.t,
    :sent => number(),
    :delivered => number(),
    :opened => number(),
    :clicked => number(),
    :bounced => number(),
    :complained => number()
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetDomainStats200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :totalSent,
    :totalDelivered,
    :totalOpened,
    :totalClicked,
    :totalBounced,
    :totalComplained,
    :deliveryRate,
    :openRate,
    :clickRate,
    :bounceRate,
    :complaintRate
  ]

  @type t :: %__MODULE__{
    :totalSent => number(),
    :totalDelivered => number(),
    :totalOpened => number(),
    :totalClicked => number(),
    :totalBounced => number(),
    :totalComplained => number(),
    :deliveryRate => number(),
    :openRate => number(),
    :clickRate => number(),
    :bounceRate => number(),
    :complaintRate => number()
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetDomains200ResponseInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :teamId,
    :autoRouting,
    :routes,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :teamId => String.t,
    :autoRouting => boolean() | nil,
    :routes => [Unsent.Types.GetDomains200ResponseInnerRoutesInner.t],
    :createdAt => String.t,
    :updatedAt => String.t
  }


  def decode(value) do
    value
     
  end
end

defmodule Unsent.Types.GetDomains200ResponseInnerRoutesInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :domainId,
    :providerConnectionId,
    :weight,
    :isActive,
    :status,
    :provider,
    :region,
    :clickTracking,
    :openTracking,
    :publicKey,
    :dkimStatus,
    :spfDetails,
    :dmarcAdded,
    :isVerifying,
    :errorMessage,
    :subdomain,
    :dnsRecords,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :domainId => String.t,
    :providerConnectionId => String.t,
    :weight => integer(),
    :isActive => boolean(),
    :status => String.t,
    :provider => String.t,
    :region => String.t | nil,
    :clickTracking => boolean() | nil,
    :openTracking => boolean() | nil,
    :publicKey => String.t | nil,
    :dkimStatus => String.t | nil,
    :spfDetails => String.t | nil,
    :dmarcAdded => boolean() | nil,
    :isVerifying => boolean() | nil,
    :errorMessage => String.t | nil,
    :subdomain => String.t | nil,
    :dnsRecords => [Unsent.Types.GetDomains200ResponseInnerRoutesInnerDnsRecordsInner.t],
    :createdAt => String.t,
    :updatedAt => String.t
  }


  def decode(value) do
    value
     
  end
end

defmodule Unsent.Types.GetDomains200ResponseInnerRoutesInnerDnsRecordsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :name,
    :value,
    :ttl,
    :priority,
    :status,
    :recommended
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :name => String.t,
    :value => String.t,
    :ttl => String.t,
    :priority => String.t | nil,
    :status => String.t,
    :recommended => boolean() | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetHealth200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :status,
    :uptime,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :uptime => number(),
    :timestamp => number()
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetSettings200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :plan,
    :dailyEmailLimit,
    :monthlyEmailLimit
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :plan => String.t,
    :dailyEmailLimit => number(),
    :monthlyEmailLimit => number()
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetTemplates200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :data
  ]

  @type t :: %__MODULE__{
    :data => [Unsent.Types.GetTemplates200ResponseDataInner.t]
  }


  def decode(value) do
    value
     
  end
end

defmodule Unsent.Types.GetTemplates200ResponseDataInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :subject,
    :html,
    :content,
    :teamId,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :subject => String.t,
    :html => String.t | nil,
    :content => String.t | nil,
    :teamId => String.t,
    :createdAt => String.t,
    :updatedAt => String.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.GetVersion200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :version,
    :environment,
    :nodeVersion,
    :platform,
    :arch,
    :timestamp,
    :versions,
    :memory
  ]

  @type t :: %__MODULE__{
    :version => String.t,
    :environment => String.t | nil,
    :nodeVersion => String.t,
    :platform => String.t,
    :arch => String.t,
    :timestamp => String.t,
    :versions => %{optional(String.t) => String.t},
    :memory => Unsent.Types.GetVersion200ResponseMemory.t
  }


  def decode(value) do
    value
     
  end
end

defmodule Unsent.Types.GetVersion200ResponseMemory do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :rss,
    :heapTotal,
    :heapUsed,
    :external
  ]

  @type t :: %__MODULE__{
    :rss => number(),
    :heapTotal => number(),
    :heapUsed => number(),
    :external => number()
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.ListEmailsDomainIdParameter do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.ScheduleCampaignRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :scheduledAt,
    :batchSize
  ]

  @type t :: %__MODULE__{
    :scheduledAt => String.t | nil,
    :batchSize => integer() | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.SendEmailRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :to,
    :from,
    :subject,
    :templateId,
    :variables,
    :replyTo,
    :cc,
    :bcc,
    :text,
    :html,
    :headers,
    :attachments,
    :scheduledAt,
    :inReplyToId
  ]

  @type t :: %__MODULE__{
    :to => Unsent.Types.SendEmailRequestTo.t,
    :from => String.t,
    :subject => String.t | nil,
    :templateId => String.t | nil,
    :variables => %{optional(String.t) => String.t} | nil,
    :replyTo => Unsent.Types.SendEmailRequestTo.t | nil,
    :cc => Unsent.Types.SendEmailRequestTo.t | nil,
    :bcc => Unsent.Types.SendEmailRequestTo.t | nil,
    :text => String.t | nil,
    :html => String.t | nil,
    :headers => %{optional(String.t) => String.t} | nil,
    :attachments => [map()] | nil,
    :scheduledAt => DateTime.t | nil,
    :inReplyToId => String.t | nil
  }


  def decode(value) do
    value
     
     
     
     
  end
end

defmodule Unsent.Types.SendEmailRequestTo do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.SuccessResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success
  ]

  @type t :: %__MODULE__{
    :success => boolean()
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.UpdateContactBook200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.UpdateContactBookRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :emoji,
    :properties
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :emoji => String.t | nil,
    :properties => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.UpdateContactRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :firstName,
    :lastName,
    :properties,
    :subscribed
  ]

  @type t :: %__MODULE__{
    :firstName => String.t | nil,
    :lastName => String.t | nil,
    :properties => %{optional(String.t) => String.t} | nil,
    :subscribed => boolean() | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.UpdateDomainRouteRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :weight,
    :clickTracking,
    :openTracking
  ]

  @type t :: %__MODULE__{
    :weight => integer() | nil,
    :clickTracking => boolean() | nil,
    :openTracking => boolean() | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.UpdateTemplateRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :subject,
    :html,
    :content
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :subject => String.t | nil,
    :html => String.t | nil,
    :content => String.t | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.UpdateWebhookRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :url,
    :description,
    :eventTypes,
    :active,
    :rotateSecret,
    :secret
  ]

  @type t :: %__MODULE__{
    :url => Uri | nil,
    :description => String.t | nil,
    :eventTypes => [String.t] | nil,
    :active => boolean() | nil,
    :rotateSecret => boolean() | nil,
    :secret => String.t | nil
  }


  def decode(value) do
    value
     
  end
end

defmodule Unsent.Types.Webhook do
  @moduledoc """
  Webhook details
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :url,
    :description,
    :eventTypes,
    :status,
    :secret,
    :apiVersion,
    :consecutiveFailures,
    :lastSuccessAt,
    :lastFailureAt,
    :createdAt,
    :updatedAt,
    :teamId,
    :createdByUserId
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :url => String.t,
    :description => String.t | nil,
    :eventTypes => [String.t],
    :status => String.t,
    :secret => String.t,
    :apiVersion => String.t | nil,
    :consecutiveFailures => number(),
    :lastSuccessAt => String.t | nil,
    :lastFailureAt => String.t | nil,
    :createdAt => String.t,
    :updatedAt => String.t,
    :teamId => String.t,
    :createdByUserId => String.t | nil
  }

  def decode(value) do
    value
  end
end

defmodule Unsent.Types.WebhookCall do
  @moduledoc """
  Webhook call details
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :type,
    :createdAt,
    :updatedAt,
    :teamId,
    :status,
    :webhookId,
    :payload,
    :attempt,
    :nextAttemptAt,
    :lastError,
    :responseStatus,
    :responseTimeMs,
    :responseText
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :type => String.t,
    :createdAt => String.t,
    :updatedAt => String.t,
    :teamId => String.t,
    :status => String.t,
    :webhookId => String.t,
    :payload => String.t,
    :attempt => number(),
    :nextAttemptAt => String.t | nil,
    :lastError => String.t | nil,
    :responseStatus => number() | nil,
    :responseTimeMs => number() | nil,
    :responseText => String.t | nil
  }

  def decode(value) do
    value
  end
end

